### ISSUE TITLE
Does not compile with Sparkfun ATSAMD21G selected as board

### ISSUE THREAD

**Issue by ssnyde** [sparkfun/SparkFun_LTE_Shield_Arduino_Library#1]
### Subject of the issue
Verify compile throws errors.  SoftwareSerial is not #ifdef'ed out in all places, and it looks like this does not exist for ATSAMD21G boards.  After modifying the library so that SoftwareSerial is not used anywhere using #ifdef, other compiler errors are thrown around various types.

### Your workbench
* What platform are you using?
Arduino 1.8.8
* What version of the device are you using? Is there a firmware version?
* How is the device wired to your platform?
Sparkfun ATSAMD21G Breakout board
* How is everything being powered?
From ATSAMD21G with USB power
* Are there any additional details that may help us help you?

### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue to a gist.
Download Arduino 1.8.8, install ATSAMD21G support via Sparkfun instructions, try and compile 00_Register_Operator example, using Serial1 for LTE board and SerialUSB for console.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ssnyde** [comment]
[atsamd21_issue.tar.gz](https://github.com/sparkfun/SparkFun_LTE_Shield_Arduino_Library/files/2664592/atsamd21_issue.tar.gz)

**Comment by romanrobles** [comment]
Using Arduino 1.8.7 with Arduino Primo and Simblee - same problem.

**Comment by jimblom** [comment]
Thanks for filing the issue @ssnyde !

I've pushed a couple new commits and published a new 1.1.0 release to support the SAMD21. The release may take a bit to hit Arduino's library manager, but you can download the updated files in the src folder to try it out.

The 00_Register_Operator.ino example was also modified to more-easily use on a SAMD21 as well. To use it with the SAMD21:

* Comment out line beginning with `SoftwareSerial lteSerial`
* Set `SerialMonitor` to `SerialUSB`
* Set `LTEShieldSerial` to `Serial1` (also set Serial-select switch on shield to "HARD")
* (Optional) Set the `lte.begin` baud rate to 115200 (hardware port can handle it!)

It's working for me on the SparkFun SAMD21 Dev Breakout.

Closing for now. Feel free to re-open if it's still not compiling/working for you.
