### ISSUE TITLE
Errors in Arduino library for SparkFun LTE CAT M1/NB-IoT Shield - SARA-R4

### ISSUE THREAD

**Issue by ROSW6341** [sparkfun/SparkFun_LTE_Shield_Arduino_Library#2]
Many functions in the current library do not free allocated memory before returning. While waiting for my order to arrive I've made a minimal set of changes to correct that and attached a patch file in src.zip. It also includes added code for hwReset() and some other minor modifications. If you have any questions or wish to discuss this in more detail please feel free to contact me at <mailto:billk@rosw.com>.

The code compiles without error using an ESP32 platform but has not been tested (still waiting for the SARA-R4 shield to arrive).

Note - I've worked as an embedded systems developer for over 30 years under the trade name R O SoftWare.  The modifications (for the most part) are the minimal needed to correct the memory leakage issue.  Once approved and tested they could use some additional cleanup.

[src.zip](https://github.com/sparkfun/SparkFun_LTE_Shield_Arduino_Library/files/2692105/src.zip)

**Comment by jimblom** [comment]
Thanks @ROSW6341, these fixes are fantastic!

I've pulled them into commit b062a77, and have upped the library release to 1.1.1 to get them into the Arduino library manager as soon as possible.

**Comment by ROSW6341** [comment]
Found some additional memory leaks and a couple of errors introduced with the last patch.  I hope this one gets everything cleared up.  Everything compiles without errors but has not been tested.
[src.zip](https://github.com/sparkfun/SparkFun_LTE_Shield_Arduino_Library/files/2703916/src.zip)
